# Site Settings
title: Ortega Hoops
email: ortegahoops2020@gmail.com
description: >
  A guide to getting started with Jekyll.
baseurl: "/"
url: "http://ortegahoops.github.io"
twitter_username: #N/A
github_username: #N/A
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
